# libmosaic build script
Import (['env', 'curs_env', 'cat_env'])

# the mosaic libraries
color = curs_env.SharedLibrary ('libmosaic_color', 'color.c')
mosaic = env.SharedLibrary ('libmosaic', 'mosaic.c')
stream_io = env.SharedLibrary ('libmosaic_stream_io', 'stream_io.c')
curs_mos = curs_env.SharedLibrary ('libmosaic_curses', 'curs_mos.c')

# the moscat application
cat_src = 'moscat.c'
moscat = cat_env.Program ('moscat', cat_src)

Default ([mosaic, curs_mos, color, stream_io, moscat])

## INSTALL STUFF ##
# includes -> *.h
includes = Glob ('#include/*.h')

# pkg-config files -> *.pc
pkgconfigs = Glob ('#pkgconfigs/*.pc')

curs_env.Install ('/usr/bin', moscat)
curs_env.Install ('/usr/lib', [mosaic, curs_mos, color, stream_io])
curs_env.Install ('/usr/include', includes)
curs_env.Install ('/usr/share/pkgconfig', pkgconfigs)
# targets: install{,-bin,-lib,-include}
curs_env.Alias ('install-lib', '/usr/lib')
curs_env.Alias ('install-bin', '/usr/bin')
curs_env.Alias ('install-include', '/usr/include')
curs_env.Alias ('install-pkgconfig', '/usr/share/pkgconfig')
curs_env.Alias ('install', ['install-lib', 'install-include', 'install-bin', 'install-pkgconfig'])
