# libmosaic build script
Import (['env', 'curs_env', 'cat_env'])

# the mosaic libraries
color = curs_env.SharedLibrary ('libmosaic_color', 'color.c')
mosaic = env.SharedLibrary ('libmosaic', 'mosaic.c')
stream_io = env.SharedLibrary ('libmosaic_stream_io', 'stream_io.c')

# the moscat application
cat_src = 'moscat.c'
moscat = cat_env.Program ('moscat', cat_src)

Default ([mosaic, color, stream_io, moscat])

## INSTALL STUFF ##
# includes -> *.h
includes = Glob ('#include/*.h')

# pkg-config files -> *.pc
pkgconfigs = Glob ('#pkgconfigs/*.pc')

env.Install ('/usr/bin', moscat)
env.Install ('/usr/lib', [mosaic, color, stream_io])
env.Install ('/usr/include/mosaic', includes)
env.Install ('/usr/share/pkgconfig', pkgconfigs)
# targets: install{,-bin,-lib,-include}
env.Alias ('install-lib', '/usr/lib')
env.Alias ('install-bin', '/usr/bin')
env.Alias ('install-include', '/usr/include')
env.Alias ('install-pkgconfig', '/usr/share/pkgconfig')
env.Alias ('install', ['install-lib', 'install-include', 'install-bin', 'install-pkgconfig'])
